services:
  mysql:
    image: mysql:8.0
    container_name: cliandcollect-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cliandcollect-network
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  mongodb:
    image: mongo:6.0
    container_name: cliandcollect-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_API_USER: ${MONGO_API_USER}
      MONGO_API_PASSWORD: ${MONGO_API_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - cliandcollect-network

volumes:
  mysql_data:
  mongodb_data:

networks:
  cliandcollect-network:
    name : cliandcollect-network