name: "Déploiement Docker du compose"
on:
  push:
    branches:
      - 'production' # Le workflow se déclenche pour les push sur la branche "production"
  workflow_dispatch:
    # Permet de lancer manuellement le workflow avec une branche spécifique

jobs:
  deploy:
    name: Déploiement Docker sur le serveur
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v3

      - name: Configurer la clé SSH
        # Crée un fichier contenant la clé privée pour accéder au serveur distant
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Créer le fichier .env localement
        # Génère un fichier .env contenant toutes les variables d'environnement requises pour les serveurs de BD
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
          echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" >> .env
          echo "MONGO_API_USER=${{ secrets.MONGO_API_USER }}" >> .env
          echo "MONGO_API_PASSWORD=${{ secrets.MONGO_API_PASSWORD }}" >> .env

      - name: Copier les fichiers nécessaires vers le serveur
        # Transfère les fichiers requis pour le déploiement vers le serveur distant
        # et utilise la clé privée ssh pour se connecter
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no \
            docker-compose.yml \
            docker-config/init-mongo.js \
            .env \
            ${{ vars.SSH_USER }}@${{ vars.SSH_SERVER }}:/var/www/docker-bdd

      - name: Nettoyer, arrêter et redémarrer les conteneurs sur le serveur distant
        # Arrête les conteneurs existants, nettoie les ressources inutilisées et redémarre les conteneurs à partir du docker-compose.yml.
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ vars.SSH_SERVER }} << EOF
            set -e
            # Passage en root et exécution des commandes
            sudo bash -c "
              cd /var/www/docker-bdd &&
              
              # Arrêter les conteneurs en cours
              docker compose down || true &&
              
              # Nettoyer les conteneurs et images inutilisés, sans affecter les volumes
              docker container prune --force &&
              docker image prune --all --force &&
              
              # Redémarrer les conteneurs
              docker compose up -d --build
            "
          EOF

      - name: Nettoyer les fichiers temporaires
        # Supprime la clé privée temporaire locale pour des raisons de sécurité
        if: always()
        run: rm -f private_key.pem